### ISSUE TITLE
An error occurred on the oracle-server node and node-red stopped.

### ISSUE THREAD

**Issue by TeruyukiMatsuzaki** [vtulluru/node-red-contrib-oracledb-mod#4]
The cause of the error is the loss of the oracle connection.It happened shortly after upgrading to node-red-contrib-oracledb-mod@0.6.1 and oracle instant client 19.10.

14 Apr 04:56:26 - [info] [oracledb:XXXXDB] Oracle query start execution
14 Apr 04:56:26 - [info] [oracledb:XXXXDB] Oracle query execution started
14 Apr 04:56:26 - [error] [oracledb:XXXXDB] Oracle query error: ORA-03113: end-of-file on communication channel
プロセスID: 15532942
セッションID: 3421、シリアル番号: 531
14 Apr 04:56:26 - [info] [oracle-server:3bd2bc9d.276314] Oracle server connection lost, retry in 60000 ms
14 Apr 04:57:26 - [red] Uncaught Exception:
14 Apr 04:57:26 - TypeError: requestingNode.log is not a function
    at Timeout.OracleServer.node.query [as _onTimeout] (C:\node-red\xxx\my_node-red\node_modules\node-red-contrib-oracledb-mod\lib\oracledb.js:200:28)
    at listOnTimeout (internal/timers.js:556:17)
    at processTimers (internal/timers.js:497:7)
14 Apr 04:57:27 - [info] 

OS : Windows Server 2012 R2
Node@14.5.2
Node-RED@1.3.1
node-red-contrib-oracledb-mod@0.6.1
oracle instant client 19.10

Worked around the issue by downgrading to node-red-contrib-oracledb-mod@0.5.8.
Is there any good way to solve it?

**Comment by akhiljakka** [comment]
Hi I am facing the same issue, please let me know how did you solve your issue, my node version is 0.6.3.

**Comment by TeruyukiMatsuzaki** [comment]
Hi [akhiljakka](https://github.com/akhiljakka).
Sorry, I have not been able to resolve this issue. I have downgraded to "node-red-contrib-oracledb-mod@0.5.8".
